# name of application
spring.application.name=jarurat-mailer

# Turn on Java 21 Virtual Threads for massive scalability
spring.threads.virtual.enabled=true

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/jarurat_mailer
spring.datasource.username=mailer_admin
spring.datasource.password=Jarurat@2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable a web console so we can visually look at our database later
spring.h2.console.enabled=true

# AWS SES Configuration
server.port=80
aws.region=ap-south-1
aws.ses.fromEmail=admin@horizonevent.info